<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc.proto

namespace App\Service;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>App.Service.TestRequest</code>
 */
class TestRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>bytes name = 1;</code>
     */
    private $name = '';
    /**
     * <code>int64 id = 2;</code>
     */
    private $id = 0;
    /**
     * <code>bool flag = 3;</code>
     */
    private $flag = false;

    public function __construct() {
        \GPBMetadata\Rpc::initOnce();
        parent::__construct();
    }

    /**
     * <code>bytes name = 1;</code>
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * <code>bytes name = 1;</code>
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, False);
        $this->name = $var;
    }

    /**
     * <code>int64 id = 2;</code>
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * <code>int64 id = 2;</code>
     */
    public function setId($var)
    {
        GPBUtil::checkInt64($var);
        $this->id = $var;
    }

    /**
     * <code>bool flag = 3;</code>
     */
    public function getFlag()
    {
        return $this->flag;
    }

    /**
     * <code>bool flag = 3;</code>
     */
    public function setFlag($var)
    {
        GPBUtil::checkBool($var);
        $this->flag = $var;
    }

}

