<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc.proto

namespace App\Service;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>App.Service.TestResponse</code>
 */
class TestResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>int64 status = 1;</code>
     */
    private $status = 0;

    public function __construct() {
        \GPBMetadata\Rpc::initOnce();
        parent::__construct();
    }

    /**
     * <code>int64 status = 1;</code>
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * <code>int64 status = 1;</code>
     */
    public function setStatus($var)
    {
        GPBUtil::checkInt64($var);
        $this->status = $var;
    }

}

