<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message.proto

namespace GPBMetadata;

class Message
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a7b0a0d6d6573736167652e70726f746f120b6170702e6d657373616765" .
            "22350a0b5465737452657175657374120c0a046e616d6518012001280c12" .
            "0a0a026964180220012803120c0a04666c6167180320012808221e0a0c54" .
            "657374526573706f6e7365120e0a06737461747573180120012803620670" .
            "726f746f33"
        ));

        static::$is_initialized = true;
    }
}

