<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc.proto

namespace GPBMetadata;

class Rpc
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Message::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0a6e0a097270632e70726f746f120b4170702e53657276696365324c0a0b" .
            "5465737453657276696365123d0a045465737412182e4170702e4d657373" .
            "6167652e54657374526571756573741a192e4170702e4d6573736167652e" .
            "54657374526573706f6e73652200620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

