<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc.proto

namespace GPBMetadata;

class Rpc
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0ac5010a097270632e70726f746f120b4170702e5365727669636522350a" .
            "0b5465737452657175657374120c0a046e616d6518012001280c120a0a02" .
            "6964180220012803120c0a04666c6167180320012808221e0a0c54657374" .
            "526573706f6e7365120e0a06737461747573180120012803324c0a0b5465" .
            "737453657276696365123d0a045465737412182e4170702e536572766963" .
            "652e54657374526571756573741a192e4170702e536572766963652e5465" .
            "7374526573706f6e73652200620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

