<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/message.proto

namespace GPBMetadata\Proto;

class Message
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a81010a1370726f746f2f6d6573736167652e70726f746f120b6170702e" .
            "6d65737361676522350a0b5465737452657175657374120c0a046e616d65" .
            "18012001280c120a0a026964180220012803120c0a04666c616718032001" .
            "2808221e0a0c54657374526573706f6e7365120e0a067374617475731801" .
            "20012803620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

