<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/rpc.proto

namespace GPBMetadata\Proto;

class Rpc
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0acb010a0f70726f746f2f7270632e70726f746f120b6170702e73657276" .
            "69636522350a0b5465737452657175657374120c0a046e616d6518012001" .
            "280c120a0a026964180220012803120c0a04666c6167180320012808221e" .
            "0a0c54657374526573706f6e7365120e0a06737461747573180120012803" .
            "324c0a0b5465737453657276696365123d0a045465737412182e6170702e" .
            "736572766963652e54657374526571756573741a192e6170702e73657276" .
            "6963652e54657374526573706f6e73652200620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

